name: AWS OIDC Test

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  aws-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::636467504913:role/Githubaction
          aws-region: ap-south-1

      - name: Check AWS identity
        run: aws sts get-caller-identity
